server.port=8081

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/

app.municipio.nome-identificador=SAO_FELIPE
app.municipio.queue-name=fila_sao_felipe
app.notifications.ignore-self-executor=false
