package io.github.regulacao_marcarcao.regulacao_marcacao.entity.enums;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public enum EspecialidadesEnum {
    // --- ESPECIALIDADES MÉDICAS (Exemplos) ---
    ANGIOLOGISTA(ItemCategoria.ESPECIALIDADE_MEDICA, "Angiologista"),
    CARDIOLOGISTA(ItemCategoria.ESPECIALIDADE_MEDICA, "Cardiologista"),
    ENDOCRINOLOGISTA(ItemCategoria.ESPECIALIDADE_MEDICA, "Endocrinologista"),
    GASTROENTEROLOGISTA(ItemCategoria.ESPECIALIDADE_MEDICA, "Gastroenterologista"),
    MASTOLOGISTA(ItemCategoria.ESPECIALIDADE_MEDICA, "Mastologista"),
    DERMATOLOGISTA(ItemCategoria.ESPECIALIDADE_MEDICA, "Dermatologista"),
    PROCEDIMENTO_DERMATOLOGISTA(ItemCategoria.ESPECIALIDADE_MEDICA, "Procedimento Dermatologia"),
    NEFROLOGISTA(ItemCategoria.ESPECIALIDADE_MEDICA, "Nefrologista"),
    ORTOPEDISTA(ItemCategoria.ESPECIALIDADE_MEDICA, "Ortopedista"),
    OFTALMOLOGISTA(ItemCategoria.ESPECIALIDADE_MEDICA, "Oftalmologista"),
    NEUROLOGISTA(ItemCategoria.ESPECIALIDADE_MEDICA, "Neurologista"),
    NEUROPEDIATRIA(ItemCategoria.ESPECIALIDADE_MEDICA, "Neuropediatria"),
    PEDIATRIA(ItemCategoria.ESPECIALIDADE_MEDICA, "Pediatria"),
    PROCTOLOGISTA(ItemCategoria.ESPECIALIDADE_MEDICA, "Proctologista"),
    GINECOLOGISTA(ItemCategoria.ESPECIALIDADE_MEDICA, "Ginecologista"),

    OTORRINOLARINGOLOGISTA(ItemCategoria.ESPECIALIDADE_MEDICA, "Otorrinolaringologista"),
    UROLOGISTA(ItemCategoria.ESPECIALIDADE_MEDICA, "Urologista"),
    REUMATOLOGISTA(ItemCategoria.ESPECIALIDADE_MEDICA, "Reumatologista"),
    PNEUMOLOGISTA(ItemCategoria.ESPECIALIDADE_MEDICA, "Pneumologista"),
    HEMATOLOGISTA(ItemCategoria.ESPECIALIDADE_MEDICA, "Hematologista"),
    CONSULTA_OFTALMOLOGICA_REFRACAO(ItemCategoria.ESPECIALIDADE_MEDICA, "Consulta Oftalmológica (Refração)"),
    CIRURGIAO_GERAL(ItemCategoria.ESPECIALIDADE_MEDICA, "Cirurgião Geral"),
    ALERGOLOGISTA(ItemCategoria.ESPECIALIDADE_MEDICA, "Alergologista"),
    OFTALMOLOGISTA_ESPECIALISTA_EM_RETINA(ItemCategoria.ESPECIALIDADE_MEDICA, "Oftamologista Especialista em Retina"), 
    OFTALMOLOGISTA_ESPECIALISTA_EM_GLAUCOMA(ItemCategoria.ESPECIALIDADE_MEDICA, "Oftamologista Especialista em Glaucoma"), 
    RETINOLOGO(ItemCategoria.ESPECIALIDADE_MEDICA, "Retinologo"), 
    ESPECILISTA_EM_OMBRO(ItemCategoria.ESPECIALIDADE_MEDICA,"Especialista em Ombro"), 
    ESPECIALISTA_EM_JOELHO(ItemCategoria.ESPECIALIDADE_MEDICA,"Especialista em Joelho"), 
    ESPECIALISTA_EM_QUADRIL(ItemCategoria.ESPECIALIDADE_MEDICA, "Especialista em Quadril"), 
    ESPECIALISTA_EM_COLUNA(ItemCategoria.ESPECIALIDADE_MEDICA, "Especialista em Coluna"), 
    ESPECIALISTA_EM_PE(ItemCategoria.ESPECIALIDADE_MEDICA,"Especialista em Pé"), 
    ESPECIALISTA_EM_MAO(ItemCategoria.ESPECIALIDADE_MEDICA, "Especialista em Mão"), 
    ESPECIASTA_EM_REDUCAO_DE_MAMA(ItemCategoria.ESPECIALIDADE_MEDICA, "Especialista em Redução de Mama"), 
    ONCOLOGISTA(ItemCategoria.ESPECIALIDADE_MEDICA, "Oncologista"), 

    // --- EXAMES OU PROCEDIMENTOS (Existentes) ---
    DOPPLER(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Doppler"),
    MAMOGRAFIA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Mamografia"),
    HOLTER(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Holter"),
    TESTE_ERGOMETRICO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Teste Ergométrico"),
    MAPA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "M.A.P.A."),
    TOMOGRAFIA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Tomografia Computadorizada"),
    TOMOGRAFIA_TORAX(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Tomografia Tórax"),
    RESSONANCIA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Ressonância Magnética"),
    CINTILOGRAFIA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Cintilografia"),
    ELETRONEUROMIOGRAFIA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Eletroneuromiografia"),
    CATETERISMO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Cateterismo"),
    HEMOGRAMA_COMPLETO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Hemograma Completo"),
    GLICEMIA_JEJUM(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Glicemia de Jejum"),
    HEMOGLOBINA_GLICADA_HBA1C(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Hemoglobina Glicada (HbA1c)"),
    COLESTEROL_TOTAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Colesterol Total"),
    HDL_COLESTEROL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "HDL Colesterol"),
    LDL_COLESTEROL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "LDL Colesterol"),
    VLDL_COLESTEROL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "VLDL Colesterol"),
    TRIGLICERIDEOS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Triglicerídeos"),
    UREIA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Ureia"),
    CREATININA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Creatinina"),
    SODIO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Sódio"),
    POTASSIO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Potássio"),
    ACIDO_URICO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Ácido Úrico"),
    SUMARIO_DE_URINA_EAS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Sumário de Urina (EAS)"),
    UROCULTURA_COM_ANTIBIOGRAMA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Urocultura com Antibiograma"),
    PARASITOLOGICO_DE_FEZES(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Parasitológico de Fezes"),
    PARASITOLOGICO_DE_FEZES_BAERMANN(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Parasitológico de Fezes C/ Baermann"),

    PESQUISA_SANGUE_OCULTO_FEZES(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Sangue Oculto nas Fezes"),
    TESTE_RAPIDO_GRAVIDEZ_TIG(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Teste Rápido de Gravidez (TIG)"),
    TESTE_RAPIDO_HIV(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Teste Rápido para HIV"),
    SOROLOGIA_HIV(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Sorologia para HIV"),
    TESTE_RAPIDO_SIFILIS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Teste Rápido para Sífilis"),
    VDRL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "VDRL"),
    TESTE_RAPIDO_HEPATITE_B(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Teste Rápido para Hepatite B"),
    HBSAG(ItemCategoria.EXAME_OU_PROCEDIMENTO, "HBsAg"),
    ANTI_HBS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Anti-HBs"),
    TESTE_RAPIDO_HEPATITE_C(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Teste Rápido para Hepatite C"),
    ANTI_HCV(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Anti-HCV"),
    TSH_HORMONIO_TIREOESTIMULANTE(ItemCategoria.EXAME_OU_PROCEDIMENTO, "TSH"),
    T4_LIVRE(ItemCategoria.EXAME_OU_PROCEDIMENTO, "T4 Livre"),
    PSA_TOTAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "PSA Total"),
    PSA_LIVRE(ItemCategoria.EXAME_OU_PROCEDIMENTO, "PSA Livre"),
    BACILOSCOPIA_DE_ESCARRO_BAAR(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Baciloscopia de Escarro (BAAR)"),
    CULTURA_DE_ESCARRO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Cultura de Escarro"),
    ELETROCARDIOGRAMA_ECG(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Eletrocardiograma (ECG)"),
    COLPOSCOPIA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Colposcopia"),
    BIOPSIA_COLO_UTERINO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Biópsia de Colo Uterino"),
    MAMOGRAFIA_BILATERAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Mamografia Bilateral"),
    ULTRASSONOGRAFIA_PARTES_MOLES(ItemCategoria.EXAME_OU_PROCEDIMENTO, "USG Partes Mole"),
    ULTRASSONOGRAFIA_ABDOMINAL_TOTAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "USG Abdominal Total"),
    ULTRASSONOGRAFIA_ABDOMEN_SUPERIOR(ItemCategoria.EXAME_OU_PROCEDIMENTO, "USG Abdômen Superior"),
    ULTRASSONOGRAFIA_PELVICA_VIA_ABDOMINAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "USG Pélvica (Abdominal)"),
    ULTRASSONOGRAFIA_PELVICA_TRANSVAGINAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "USG Pélvica (Transvaginal)"),
    ULTRASSONOGRAFIA_OBSTETRICA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "USG Obstétrica"),
    ULTRASSONOGRAFIA_VIAS_URINARIAS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "USG Vias Urinárias"),
    ULTRASSONOGRAFIA_PROSTATA_VIA_ABDOMINAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "USG Próstata (Abdominal)"),
    ULTRASSONOGRAFIA_TIREOIDE(ItemCategoria.EXAME_OU_PROCEDIMENTO, "USG Tireoide"),
    ULTRASSONOGRAFIA_ARTICULAR(ItemCategoria.EXAME_OU_PROCEDIMENTO, "USG Articular"),
    ULTRASSONOGRAFIA_DOPPLER_ARTERIAL_MEMBRO_INFERIOR_UNILATERAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "USG Doppler Arterial MI Unilateral"),
    ULTRASSONOGRAFIA_DOPPLER_ARTERIAL_MEMBRO_INFERIOR_BILATERAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "USG Doppler Arterial MI Bilateral"),
    ULTRASSONOGRAFIA_DOPPLER_VENOSO_MEMBRO_INFERIOR_UNILATERAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "USG Doppler Venoso MI Unilateral"),
    ULTRASSONOGRAFIA_DOPPLER_VENOSO_MEMBRO_INFERIOR_BILATERAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "USG Doppler Venoso MI Bilateral"),
    ULTRASSONOGRAFIA_DOPPLER_CAROTIDAS_E_VERTEBRAIS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "USG Doppler Carótidas e Vertebrais"),
    ULTRASSONOGRAFIA_MAMARIA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "USG Mamária"),
   
    USG_PUNHO_ESQUERDO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "USG Punho Esquerdo"),
    USG_PUNHO_DIREITO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "USG Punho Direito"),
    USG_OMBRO_DIREITO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "USG Ombro Direito"),
    USG_OMBRO_ESQUERDO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "USG Ombro Esquerdo"),
    USG_JOELHO_ESQUERDO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "USG Joelho Esquerdo"),
    USG_JOELHO_D(ItemCategoria.EXAME_OU_PROCEDIMENTO, "USG Joelho Direito"),
    USG_JOELHO_E(ItemCategoria.ESPECIALIDADE_MEDICA, "USG Joelho Esquerdo_"),
    USG_DORSAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "USG Dorsal"),
    USG_UMBILICAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "USG Umbilical"),
    USG_DE_MAO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "USG de Mão"),

    //RAIO X
    RAIO_X_TORAX_PA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Raio-X Tórax PA"),
    RAIO_X_TORAX_PA_PERFIL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Raio-X Tórax PA/Perfil"),
    RAIO_X_SEIOS_DA_FACE(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Raio-X Seios da Face"),
    RAIO_X_COLUNA_CERVICAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Raio-X Coluna Cervical"),
    RAIO_X_COLUNA_DORSAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Raio-X Coluna Dorsal"),
    RAIO_X_COLUNA_LOMBO_SACRA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Raio-X Coluna Lombo-Sacra"),
    RAIO_X_ABDOMEN_SIMPLES(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Raio-X Abdômen Simples"),
    RAIO_X_ABDOMEN_AGUDO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Raio-X Abdômen Agudo"),
    RAIO_X_ARTICULACAO_COXO_FEMURAL_BACIA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Raio-X Bacia"),
    RAIO_X_JOELHO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Raio-X Joelho"),
    RAIO_X_MAO_OU_QUIRODACTILOS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Raio-X Mão/Quirodáctilos"),
    RAIO_X_PE_OU_PODODACTILOS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Raio-X Pé/Pododáctilos"),
    RAIO_X_CALCANEO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Raio-X Calcaneo"),
    RAIO_X_COLUNA_LOMBAR(ItemCategoria.EXAME_OU_PROCEDIMENTO,"Raio-X Coluna Lombar"),
    RAIO_X_OMBRO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Raio-X Ombro"),
    RAIO_X_CAVUM(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Raio-X Cavum"),
    RAIO_X_COLUNA_TORACICA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Raio-X Coluna Toracica"),
    RAIO_X_ESCAPULA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Raio-X Escapula"),
    RAIO_X_REGIAO_CERVICAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Raio-X Região Cervical"),
    RAIO_X_PUNHO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Raio-X de Punho"),

    TESTE_ERGOMETRICO_CONVENCIONAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Teste Ergométrico Convencional"),
    HOLTER_24_HORAS_3_CANAIS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Holter 24 Horas (3 Canais)"),
    MAPA_24_HORAS_MONITORIZACAO_AMBULATORIAL_PRESSAO_ARTERIAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "MAPA 24 Horas"),
    ENDOSCOPIA_DIGESTIVA_ALTA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Endoscopia Digestiva Alta"),
    ENDOSCOPIA_DIGESTIVA_ALTA_COM_BIOPSIA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Endoscopia Digestiva Alta com Biópsia"),
    COLONOSCOPIA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Colonoscopia"),
    COLONOSCOPIA_COM_BIOPSIA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Colonoscopia com Biópsia"),
    AUDIOMETRIA_TONAL_LIMIAR_COM_TESTES_DE_DISCRIMINACAO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Audiometria Tonal e Vocal"),
    IMPEDANCIOMETRIA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Impedanciometria"),
    FUNDOSCOPIA_BINOCULAR_INDIRETA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Fundoscopia Binocular Indireta"),
    TONOMETRIA_APLANACAO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Tonometria de Aplanação"),
    DENSITOMETRIA_OSSEA_COLUNA_E_FEMUR(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Densitometria Óssea"),
    ECOCARDIOGRAMA_TRANSTORACICO_MODO_M_BIDIMENSIONAL_DOPPLER(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Ecocardiograma Transtorácico com Doppler"),
    ESPIROMETRIA_PROVA_VENTILATORIA_COMPLETA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Espirometria Completa"),
    ELETROENCEFALOGRAMA_CONVENCIONAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Eletroencefalograma Convencional"),
    TOMOGRAFIA_COMPUTADORIZADA_CRANIO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "TC Crânio"),
    TOMOGRAFIA_COMPUTADORIZADA_DO_CRANIO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Tomografia Computadorizada do Crânio"),
    TOMOGRAFIA_COMPUTADORIZADA_TORAX(ItemCategoria.EXAME_OU_PROCEDIMENTO, "TC Tórax"),
    TOMOGRAFIA_COMPUTADORIZADA_ABDOME_SUPERIOR(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Tomografia Computadorizada Abdômen Superior"),
    TOMOGRAFIA_COMPUTADORIZADA_ABDOMEN_TOTAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "TC Abdômen Total"),
    RESSONANCIA_MAGNETICA_CRANIO_ENCEFALO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "RM Crânio/Encéfalo"),
    RESSONANCIA_MAGNETICA_COLUNA_CERVICAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "RM Coluna Cervical"),
    RESSONANCIA_MAGNETICA_COLUNA_LOMBAR(ItemCategoria.EXAME_OU_PROCEDIMENTO, "RM Coluna Lombar"),
    RESSONANCIA_MAGNETICA_JOELHO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "RM Joelho"),
    CINTILOGRAFIA_MIOCARDIO_PERFUSAO_REPOUSO_ESTRESSE(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Cintilografia Miocárdio (Repouso/Estresse)"),
    CINTILOGRAFIA_TIREOIDE_CAPTACAO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Cintilografia Tireoide com Captação"),
    CINTILOGRAFIA_OSSEA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Cintilografia Óssea"),
    ELETRONEUROMIOGRAFIA_MEMBROS_SUPERIORES(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Eletroneuromiografia MMSS"),
    ELETRONEUROMIOGRAFIA_MEMBROS_INFERIORES(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Eletroneuromiografia MMII"),
    CATETERISMO_CARDIACO_ESQUERDO_DIAGNOSTICO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Cateterismo Cardíaco Diagnóstico"),
    AVALIACAO_URODINAMICA_COMPLETA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Avaliação Urodinâmica Completa"),
    TGO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "TGO"),
    TGP(ItemCategoria.EXAME_OU_PROCEDIMENTO, "TGP"),
    FATOR_REUMATOIDE(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Fator Reumatoide"),
    PESQUISA_OVOS_CISTOS_PARASITAS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Ovos, Cistos e Parasitas"),
    GAMA_GT(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Gama GT"),
    COAGULOGRAMA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Coagulograma"),
    ASLO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "ASLO"),
    CALCIO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Cálcio"),
    FOSFATASE_ALCALINA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Fosfatase Alcalina"),
    BILIRRUBINA_TOTAL_FRACOES(ItemCategoria.EXAME_OU_PROCEDIMENTO,"Bilirrubina total e frações"),
    TIPO_SANGUINEO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Tipo Sanguíneo"),
    TP(ItemCategoria.EXAME_OU_PROCEDIMENTO, "TP"),
    TTPA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "TTPA"),
    EXERESE_PEQUENAS_LESOES_PELE_ANATOMOPATOLOGICO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Exerese Pequenas Lesões de Pele + AP"),

    // --- NOVOS EXAMES E PROCEDIMENTOS ---
    ANALISE_CARACTERES_FISICOS_ELEMENTOS_SEDIMENTO_URINA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Análise de Caracteres Físicos, Elementos e Sedimento da Urina"),
    ANTIBIOGRAMA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Antibiograma"),
    BACILOSCOPIA_DIRETA_BAAR_TUBERCULOS_CONTROLE(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Baciloscopia Direta p/ BAAR Tuberculose (Controle)"),
    BACILOSCOPIA_DIRETA_BAAR_TUBERCULOSE_DIAGNOSTICA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Baciloscopia p/ BAAR Direta Tuberculose (Diagnóstica)"),
    BACTEROSCOPIA_GRAM(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Bacterioscopia (Gram)"),
    CLEARANCE_CREATININA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Clearance de Creatinina"),
    CONTAGEM_PLAQUETAS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Contagem de Plaquetas"),
    CONTAGEM_RETICULOCITOS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Contagem de Reticulócitos"),
    CULTURA_BACTERIAS_IDENTIFICACAO_UROCULTURA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Cultura de Bactérias p/ Identificação (Urocultura)"),
    DETERMINACAO_CAPACIDADE_FIXACAO_FERRO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Determinação de Capacidade de Fixação do Ferro"),
    DETERMINACAO_CURVA_GLICEMICA_2_DOSAGENS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Determinação de Curva Glicêmica (2 Dosagens)"),
    DETERMINACAO_LATEX(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Determinação de Látex"),
    DETERMINACAO_TEMPO_COAGULACAO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Determinação de Tempo de Coagulação"),
    DETERMINACAO_TEMPO_SANGRAMENTO_IVY(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Determinação de Tempo de Sangramento de Ivy"),
    DETERMINACAO_TEMPO_SANGRAMENTO_DUKE(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Determinação de Tempo de Sangramento-Duke"),
    DETERMINACAO_TEMPO_TROMBINA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Determinação de Tempo de Trombina"),
    DETERMINACAO_VELOCIDADE_HEMOSSEDIMENTACAO_VHS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Determinação de Velocidade de Hemossedimentação (VHS)"),
    DETERMINACAO_DIRETA_REVERSA_GRUPO_ABO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Determinação Direta e Reversa de Grupo ABO"),
    DETERMINACAO_QUANTITATIVA_PROTEINA_C_REATIVA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Determinação Quantitativa de Proteína C Reativa"),
    DOSAGEM_25_HIDROXIVITAMINA_D(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de 25 Hidroxivitamina D"),
    DOSAGEM_ALBUMINA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Albumina"),
    DOSAGEM_ALFA_1_ANTITRIPSINA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Alfa-1-Antitripsina"),
    DOSAGEM_ALFA_FETOPROTEINA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Alfa-Fetoproteína"),
    DOSAGEM_AMILASE(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Amilase"),
    DOSAGEM_CALCIO_IONIZAVEL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Cálcio Ionizável"),
    DOSAGEM_COMPLEMENTO_C3(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Complemento C3"),
    DOSAGEM_COMPLEMENTO_C4(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Complemento C4"),
    DOSAGEM_CORTISOL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Cortisol"),
    DOSAGEM_CREATINOFOSFOQUINASE_CPK(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Creatinofosfoquinase (CPK)"),
    DOSAGEM_CREATINOFOSFOQUINASE_FRACAO_MB(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Creatinofosfoquinase Fração MB"),
    DOSAGEM_DEHIDROEPIANDROSTERONA_DHEA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Dehidroepiandrosterona (DHEA)"),
    DOSAGEM_DESIDROGENASE_LATICA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Desidrogenase Lática"),
    DOSAGEM_ESTRADIOL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Estradiol"),
    DOSAGEM_ESTRIOL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Estriol"),
    DOSAGEM_ESTRONA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Estrona"),
    DOSAGEM_FERRITINA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Ferritina"),
    DOSAGEM_FERRO_SERICO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Ferro Sérico"),
    DOSAGEM_FOSFATASE_ACIDA_TOTAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Fosfatase Ácida Total"),
    DOSAGEM_FOSFORO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Fósforo"),
    DOSAGEM_GONADOTROFINA_CORIONICA_HUMANA_HCG_BETA_HCG(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Gonadotrofina Coriônica Humana (HCG, Beta HCG)"),
    DOSAGEM_HAPTOGLOBINA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Haptoglobina"),
    DOSAGEM_HEMOGLOBINA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Hemoglobina"),
    DOSAGEM_HEMOGLOBINA_GLICOSILADA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Hemoglobina Glicosilada"),
    DOSAGEM_HORMONIO_FOLICULO_ESTIMULANTE_FSH(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Hormônio Folículo-Estimulante (FSH)"),
    DOSAGEM_HORMONIO_LUTEINIZANTE_LH(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Hormônio Luteinizante (LH)"),
    DOSAGEM_IMUNOGLOBULINA_A_IGA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Imunoglobulina A (IGA)"),
    DOSAGEM_IMUNOGLOBULINA_E_IGE(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Imunoglobulina E (IGE)"),
    DOSAGEM_IMUNOGLOBULINA_M_IGM(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Imunoglobulina M (IGM)"),
    DOSAGEM_INSULINA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Insulina"),
    DOSAGEM_LACTATO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Lactato"),
    DOSAGEM_LIPASE(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Lipase"),
    DOSAGEM_LITIO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Lítio"),
    DOSAGEM_MAGNESIO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Magnésio"),
    DOSAGEM_MICROALBUMINA_NA_URINA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Microalbumina na Urina"),
    DOSAGEM_MUCO_PROTEINAS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Muco-Proteínas"),
    DOSAGEM_PARATORMONIO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Paratormônio"),
    DOSAGEM_PROGESTERONA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Progesterona"),
    DOSAGEM_PROLACTINA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Prolactina"),
    DOSAGEM_PROTEINAS_URINA_24_HORAS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Proteínas (Urina de 24 Horas)"),
    DOSAGEM_PROTEINAS_TOTAIS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Proteínas Totais"),
    DOSAGEM_PROTEINAS_TOTAIS_E_FRACOES(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Proteínas Totais e Frações"),
    DOSAGEM_SULFATO_DE_HIDROEPIANDROSTERONA_DHEAS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Sulfato de Hidroepiandrosterona (DHEAS)"),
    DOSAGEM_TESTOSTERONA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Testosterona"),
    DOSAGEM_TESTOSTERONA_LIVRE(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Testosterona Livre"),
    DOSAGEM_TIREOGLOBULINA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Tireoglobulina"),
    DOSAGEM_TIROXINA_T4(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Tiroxina (T4)"),
    DOSAGEM_TRANSFERRINA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Transferrina"),
    DOSAGEM_TRIIODOTIRONINA_T3(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Triiodotironina (T3)"),
    DOSAGEM_TROPONINA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Troponina"),
    DOSAGEM_VITAMINA_B12(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Vitamina B12"),
    DOSAGEM_ZINCO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Dosagem de Zinco"),
    ELETROFORESE_DE_HEMOGLOBINA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Eletroforese de Hemoglobina"),
    ELETROFORESE_DE_LIPOPROTEINAS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Eletroforese de Lipoproteínas"),
    ERITROGRAMA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Eritrograma (Eritrócitos, Hemoglobina, Hematócrito)"),
    EXAME_CARACTERES_FISICOS_CONTAGEM_GLOBAL_ESPECIFICA_CELULAS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Exame de Caracteres Físicos, Contagem Global e Específica de Células"),
    HEMATOCRITO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Hematócrito"),
    HEMOCULTURA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Hemocultura"),
    IMUNOELETROFORESE_DE_PROTEINAS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Imunoeletroforese de Proteínas"),
    LEUCOGRAMA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Leucograma"),
    PESQUISA_ANTICORPO_IGG_ANTICARDIOLIPINA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpo IGG Anticardiolipina"),
    PESQUISA_ANTICORPO_IGM_DE_ANTICARDIOLIPINA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpo IGM de Anticardiolipina"),
    PESQUISA_ANTICORPOS_ANTI_HELICOBACTER_PYLORI(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos Anti-Helicobacter Pylori"),
    PESQUISA_ANTICORPOS_ANTI_HIV_1_HIV_2_ELISA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos Anti-HIV-1+ HIV-2 (ELISA)"),
    PESQUISA_ANTICORPOS_ANTI_HTLV_1_HTLV_2(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos Anti-HTLV-1 HTLV-2"),
    PESQUISA_ANTICORPOS_ANTINUCLEO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos Antinúcleo"),
    PESQUISA_ANTICORPOS_ANTI_SM(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos Anti-SM"),
    PESQUISA_ANTICORPOS_ANTI_SS_A_RO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos Anti-SS-A (RO)"),
    PESQUISA_ANTICORPOS_ANTI_SS_B_LA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos Anti-SS-B (LA)"),
    PESQUISA_ANTICORPOS_ANTITIREOGLOBULINA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos Antitireoglobulina"),
    PESQUISA_ANTICORPOS_CONTRA_ANTIGENO_E_VIRUS_HEPATITE_B_ANTI_HBE(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos Contra Antígeno E do Vírus da Hepatite B (Anti-HBE)"),
    PESQUISA_ANTICORPOS_CONTRA_VIRUS_HEPATITE_D_ANTI_HDV(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos Contra o Vírus da Hepatite D (Anti-HDV)"),
    PESQUISA_ANTICORPOS_CONTRA_VIRUS_SARAMPO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos Contra o Vírus do Sarampo"),
    PESQUISA_ANTICORPOS_IGG_ANTICITOMEGALOVIRUS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos IGG Anticitomegalovírus"),
    PESQUISA_ANTICORPOS_IGG_ANTILEISHMANIAS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos IGG Antileishmanias"),
    PESQUISA_ANTICORPOS_IGG_ANTITOXOPLASMA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos IGG Antitoxoplasma"),
    PESQUISA_ANTICORPOS_IGG_ANTITRYPANOSOMA_CRUZI(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos IGG Antitrypanosoma Cruzi"),
    PESQUISA_ANTICORPOS_IGG_CONTRA_ANTIGENO_CENTRAL_VIRUS_HEPATITE_B_ANTI_HBC_IGG(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos IGG Contra Antígeno Central do Vírus da Hepatite B (Anti-HBC-IGG)"),
    PESQUISA_ANTICORPOS_IGG_CONTRA_VIRUS_HEPATITE_A_HAV_IGG(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos IGG Contra o Vírus da Hepatite A (HAV-IGG)"),
    PESQUISA_ANTICORPOS_IGG_CONTRA_VIRUS_RUBEOLA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos IGG Contra o Vírus da Rubéola"),
    PESQUISA_ANTICORPOS_IGG_CONTRA_VIRUS_VARICELA_HERPES_ZOSTER(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos IGG Contra o Vírus da Varicela-Herpes Zoster"),
    PESQUISA_ANTICORPOS_IGG_CONTRA_VIRUS_EPSTEIN_BARR(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos IGG Contra o Vírus Epstein-Barr"),
    PESQUISA_ANTICORPOS_IGM_ANTICITOMEGALOVIRUS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos IGM Anticitomegalovírus"),
    PESQUISA_ANTICORPOS_IGM_ANTILEISHMANIAS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos IGM Antileishmanias"),
    PESQUISA_ANTICORPOS_IGM_ANTITOXOPLASMA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos IGM Antitoxoplasma"),
    PESQUISA_ANTICORPOS_IGM_ANTITRYPANOSOMA_CRUZI(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos IGM Antitrypanosoma Cruzi"),
    PESQUISA_ANTICORPOS_IGM_CONTRA_ANTIGENO_CENTRAL_VIRUS_HEPATITE_B_ANTI_HBC_IGM(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos IGM Contra Antígeno Central do Vírus da Hepatite B (Anti-HBC-IGM)"),
    PESQUISA_ANTICORPOS_IGM_CONTRA_VIRUS_HEPATITE_A_HAV_IGG(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos IGM Contra o Vírus da Hepatite A (HAV-IGG)"),
    PESQUISA_ANTICORPOS_IGM_CONTRA_VIRUS_RUBEOLA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Anticorpos IGM Contra o Vírus da Rubéola"),
    PESQUISA_ANTIGENO_CARCINOEMBRIONARIO_CEA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Antígeno Carcinoembrionário (CEA)"),
    PESQUISA_ANTIGENO_E_VIRUS_HEPATITE_B_HBEAG(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Antígeno E do Vírus da Hepatite B (HBEAG)"),
    PESQUISA_FATOR_REUMATOIDE_WAALER_ROSE(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Fator Reumatoide (Waaler-Rose)"),
    PESQUISA_FATOR_RH_INCLUI_D_FRACO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Fator RH (Inclui D Fraco)"),
    PESQUISA_HEMOGLOBINA_S(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Hemoglobina S"),
    PESQUISA_LARVAS_NAS_FEZES(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Larvas nas Fezes"),
    PESQUISA_TRIPANOSSOMA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Tripanossoma"),
    PESQUISA_TROFOZOITAS_NAS_FEZES(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Pesquisa de Trofozoitas nas Fezes"),
    PROVA_RETRACAO_COAGULO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Prova de Retração do Coágulo"),
    PROVA_DO_LACO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Prova do Laço"),
    REACAO_HEMAGLUTINACAO_TPHA_DIAGNOSTICO_SIFILIS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Reação de Hemaglutinação (TPHA) p/ Diagnóstico da Sífilis"),
    REACAO_MONTENEGRO_ID(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Reação de Montenegro ID"),
    TESTE_VDRL_DETECCAO_SIFILIS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Teste de VDRL p/ Detecção de Sífilis"),
    TESTE_DIRETO_ANTIGLOBULINA_HUMANA_TAD(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Teste Direto de Antiglobulina Humana (TAD)"),
    TESTE_FTA_ABS_IGG_DIAGNOSTICO_SIFILIS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Teste FTA-ABS IGG p/ Diagnóstico da Sífilis"),
    TESTE_FTA_ABS_IGM_DIAGNOSTICO_SIFILIS(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Teste FTA-ABS IGM p/ Diagnóstico da Sífilis"),
    TESTE_TUBERCULINICO_PPD(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Teste Tuberculínico(PPD)"),
    VDRL_DETECCAO_SIFILIS_EM_GESTANTE(ItemCategoria.EXAME_OU_PROCEDIMENTO, "VDRL p/ Detecção de Sífilis em Gestante"),

    // --- NOVOS EXAMES DE IMAGEM ---
    ANGIORESSONANCIA_CEREBRAL_ARTERIAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Angioressonância Cerebral Arterial"),
    ANGIORESSONANCIA_DE_CRANIO_ARTERIAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Angioressonância de Crânio Arterial"),
    RESSONANCIA_MAGNETICA_ARTICULACAO_TEMPORO_MANDIBULAR_BILATERAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Ressonância Magnética de Articulação Têmporo-Mandibular Bilateral"),
    RESSONANCIA_MAGNETICA_BACIA_PELVE_ABDOMEN_INFERIOR(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Ressonância Magnética Bacia/Pelve/Abdômen Inferior"),
    RESSONANCIA_MAGNETICA_COLUNA_TORACICA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Ressonância Magnética de Coluna Torácica"),
    RESSONANCIA_MAGNETICA_CORACAO_AORTA_COM_CINE(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Ressonância Magnética de Coração / Aorta c/ Cine"),
    RESSONANCIA_MAGNETICA_MEMBRO_INFERIOR_UNILATERAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Ressonância Magnética de Membro Inferior (Unilateral)"),
    RESSONANCIA_MAGNETICA_MEMBRO_SUPERIOR_UNILATERAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Ressonância Magnética de Membro Superior (Unilateral)"),
    RESSONANCIA_MAGNETICA_SELA_TURCICA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Ressonância Magnética de Sela Túrcica"),
    RESSONANCIA_MAGNETICA_TORAX(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Ressonância Magnética de Tórax"),
    RESSONANCIA_MAGNETICA_VIAS_BILIARES_COLANGIORESSONANCIA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Ressonância Magnética de Vias Biliares / Colangioressonância"),
    TOMOGRAFIA_COMPUTADORIZADA_ARTICULACOES_MEMBRO_INFERIOR(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Tomografia Computadorizada de Articulações de Membro Inferior"),
    TOMOGRAFIA_COMPUTADORIZADA_ARTICULACOES_MEMBRO_SUPERIOR(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Tomografia Computadorizada de Articulações de Membro Superior"),
    TOMOGRAFIA_COLUNA_CERVICAL(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Tomografia Coluna Cervical"),
    TOMOGRAFIA_COMPUTADORIZADA_COLUNA_CERVICAL_COM_OU_SEM_CONTRASTE(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Tomografia Computadorizada de Coluna Cervical com ou sem Contraste"),
    TOMOGRAFIA_COMPUTADORIZADA_COLUNA_LOMBOSACRA_COM_OU_SEM_CONTRASTE(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Tomografia Computadorizada de Coluna Lombosacra com ou sem Contraste"),
    TOMOGRAFIA_COMPUTADORIZADA_COLUNA_TORACICA_COM_OU_SEM_CONTRASTE(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Tomografia Computadorizada de Coluna Torácica com ou sem Contraste"),
    TOMOGRAFIA_COMPUTADORIZADA_FACE_SEIOS_DA_FACE_ARTICULACOES_TEMPO_MANDIBULARES(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Tomografia Computadorizada de Face / Seios da Face / Articulações Têmporo-Mandibulares"),
    TOMOGRAFIA_COMPUTADORIZADA_PELVE_BACIA_ABDOMEN_INFERIOR(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Tomografia Computadorizada de Pelve / Bacia / Abdômen Inferior"),
    TOMOGRAFIA_COMPUTADORIZADA_SEGMENTOS_APENDICULARES(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Tomografia Computadorizada de Segmentos Apendiculares - Braço, Antebraço, Mão, Coxa, Perna, Pé"),
    TOMOGRAFIA_COMPUTADORIZADA_SELA_TURCICA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Tomografia Computadorizada de Sela Túrcica"),
    TOMOGRAFIA_COMPUTADORIZADA_PESCOCO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Tomografia Computadorizada do Pescoço"),
    TOMOGRAFIA_POR_EMISSAO_DE_POSITRONS_PET_CT(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Tomografia por Emissão de Pósitrons - PET CT"),
    GLICOSE(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Glicose"),
    TOMOMIELOGRAFIA_COMPUTADORIZADA(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Tomomielografia Computadorizada"),
    ANGIOTOMOGRAFIA(ItemCategoria.EXAME_OU_PROCEDIMENTO,"Angiotomografia"),
    
    TOTG_75G(ItemCategoria.EXAME_OU_PROCEDIMENTO, "TOTG(75)"),
    ACIDO_FOLICO(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Ácido Fólico"),
    COLESTEROL_TOTAL_E_FRACOES(ItemCategoria.EXAME_OU_PROCEDIMENTO, "Colesterol Total e Frações"),

    ;

    private final ItemCategoria categoria;
    private final String descricao;

    EspecialidadesEnum(ItemCategoria categoria, String descricao) {
        this.categoria = categoria;
        this.descricao = descricao;
    }

    public ItemCategoria getCategoria() {
        return categoria;
    }

    public String getDescricao() {
        return descricao;
    }

    public static List<EspecialidadesEnum> getItensPorCategoria(ItemCategoria categoria) {
        return Arrays.stream(values())
                .filter(item -> item.getCategoria() == categoria)
                .collect(Collectors.toList());
    }
}
