-- INSTRUÇÕES:
-- 1. Crie um NOVO arquivo na pasta do seu projeto Java em:
--    src/main/resources/db/migration
--
-- 2. Nomeie o arquivo seguindo o padrão do Flyway. Se você já tem um V1, nomeie este como:
--    V2__Update_especialidades_check_constraint.sql
--
-- 3. Copie e cole TODO o conteúdo abaixo para dentro desse novo arquivo.

-- Passo 1: Remover a constraint antiga que não contém 'PEDIATRA'.
-- O nome da constraint é o que aparece no seu log de erro.
ALTER TABLE solicitacao_especialidade
DROP CONSTRAINT IF EXISTS solicitacao_especialidade_especialidade_solicitada_check;

-- Passo 2: Adicionar a nova constraint com a lista completa e correta de valores do seu Enum.
ALTER TABLE solicitacao_especialidade
ADD CONSTRAINT solicitacao_especialidade_especialidade_solicitada_check
CHECK (especialidade_solicitada IN (
    'ANGIOLOGISTA', 'CARDIOLOGISTA', 'ENDOCRINOLOGISTA', 'GASTROENTEROLOGISTA',
    'MASTOLOGISTA', 'DERMATOLOGISTA', 'NEFROLOGISTA', 'ORTOPEDISTA',
    'OFTALMOLOGISTA', 'NEUROLOGISTA', 'NEUROPEDIATRIA', 'PEDIATRA',
    'OTORRINOLARINGOLOGISTA', 'UROLOGISTA', 'REUMATOLOGISTA', 'PNEUMOLOGISTA',
    'HEMATOLOGISTA', 'CONSULTA_OFTALMOLOGICA_REFRACAO', 'DOPPLER', 'MAMOGRAFIA',
    'HOLTER', 'TESTE_ERGOMETRICO', 'MAPA', 'TOMOGRAFIA', 'RESSONANCIA',
    'CINTILOGRAFIA', 'ELETRONEUROMIOGRAFIA', 'CATETERISMO', 'HEMOGRAMA_COMPLETO',
    'GLICEMIA_JEJUM', 'HEMOGLOBINA_GLICADA_HBA1C', 'COLESTEROL_TOTAL', 'HDL_COLESTEROL',
    'LDL_COLESTEROL', 'VLDL_COLESTEROL', 'TRIGLICERIDEOS', 'UREIA', 'CREATININA',
    'SODIO', 'POTASSIO', 'ACIDO_URICO', 'SUMARIO_DE_URINA_EAS',
    'UROCULTURA_COM_ANTIBIOGRAMA', 'PARASITOLOGICO_DE_FEZES',
    'PESQUISA_SANGUE_OCULTO_FEZES', 'TESTE_RAPIDO_GRAVIDEZ_TIG', 'TESTE_RAPIDO_HIV',
    'SOROLOGIA_HIV', 'TESTE_RAPIDO_SIFILIS', 'VDRL', 'TESTE_RAPIDO_HEPATITE_B',
    'HBSAG', 'ANTI_HBS', 'TESTE_RAPIDO_HEPATITE_C', 'ANTI_HCV',
    'TSH_HORMONIO_TIREOESTIMULANTE', 'T4_LIVRE', 'PSA_TOTAL', 'PSA_LIVRE',
    'BACILOSCOPIA_DE_ESCARRO_BAAR', 'CULTURA_DE_ESCARRO', 'ELETROCARDIOGRAMA_ECG',
    'COLPOSCOPIA', 'BIOPSIA_COLO_UTERINO', 'MAMOGRAFIA_BILATERAL',
    'ULTRASSONOGRAFIA_PARTES_MOLES', 'ULTRASSONOGRAFIA_ABDOMINAL_TOTAL',
    'ULTRASSONOGRAFIA_ABDOMEN_SUPERIOR', 'ULTRASSONOGRAFIA_PELVICA_VIA_ABDOMINAL',
    'ULTRASSONOGRAFIA_PELVICA_TRANSVAGINAL', 'ULTRASSONOGRAFIA_OBSTETRICA',
    'ULTRASSONOGRAFIA_VIAS_URINARIAS', 'ULTRASSONOGRAFIA_PROSTATA_VIA_ABDOMINAL',
    'ULTRASSONOGRAFIA_TIREOIDE', 'ULTRASSONOGRAFIA_ARTICULAR',
    'ULTRASSONOGRAFIA_DOPPLER_ARTERIAL_MEMBRO_INFERIOR_UNILATERAL',
    'ULTRASSONOGRAFIA_DOPPLER_ARTERIAL_MEMBRO_INFERIOR_BILATERAL',
    'ULTRASSONOGRAFIA_DOPPLER_VENOSO_MEMBRO_INFERIOR_UNILATERAL',
    'ULTRASSONOGRAFIA_DOPPLER_VENOSO_MEMBRO_INFERIOR_BILATERAL',
    'ULTRASSONOGRAFIA_DOPPLER_CAROTIDAS_E_VERTEBRAIS', 'RAIO_X_TORAX_PA',
    'RAIO_X_TORAX_PA_PERFIL', 'RAIO_X_SEIOS_DA_FACE', 'RAIO_X_COLUNA_CERVICAL',
    'RAIO_X_COLUNA_DORSAL', 'RAIO_X_COLUNA_LOMBO_SACRA', 'RAIO_X_ABDOMEN_SIMPLES',
    'RAIO_X_ABDOMEN_AGUDO', 'RAIO_X_ARTICULACAO_COXO_FEMURAL_BACIA', 'RAIO_X_JOELHO',
    'RAIO_X_MAO_OU_QUIRODACTILOS', 'RAIO_X_PE_OU_PODODACTILOS',
    'TESTE_ERGOMETRICO_CONVENCIONAL', 'HOLTER_24_HORAS_3_CANAIS',
    'MAPA_24_HORAS_MONITORIZACAO_AMBULATORIAL_PRESSAO_ARTERIAL',
    'ENDOSCOPIA_DIGESTIVA_ALTA', 'ENDOSCOPIA_DIGESTIVA_ALTA_COM_BIOPSIA',
    'COLONOSCOPIA', 'COLONOSCOPIA_COM_BIOPSIA',
    'AUDIOMETRIA_TONAL_LIMIAR_COM_TESTES_DE_DISCRIMINACAO', 'IMPEDANCIOMETRIA',
    'FUNDOSCOPIA_BINOCULAR_INDIRETA', 'TONOMETRIA_APLANACAO',
    'DENSITOMETRIA_OSSEA_COLUNA_E_FEMUR',
    'ECOCARDIOGRAMA_TRANSTORACICO_MODO_M_BIDIMENSIONAL_DOPPLER',
    'ESPIROMETRIA_PROVA_VENTILATORIA_COMPLETA', 'ELETROENCEFALOGRAMA_CONVENCIONAL',
    'TOMOGRAFIA_COMPUTADORIZADA_CRANIO', 'TOMOGRAFIA_COMPUTADORIZADA_TORAX',
    'TOMOGRAFIA_COMPUTADORIZADA_ABDOMEN_TOTAL', 'RESSONANCIA_MAGNETICA_CRANIO_ENCEFALO',
    'RESSONANCIA_MAGNETICA_COLUNA_CERVICAL', 'RESSONANCIA_MAGNETICA_COLUNA_LOMBAR',
    'RESSONANCIA_MAGNETICA_JOELHO', 'CINTILOGRAFIA_MIOCARDIO_PERFUSAO_REPOUSO_ESTRESSE',
    'CINTILOGRAFIA_TIREOIDE_CAPTACAO', 'CINTILOGRAFIA_OSSEA',
    'ELETRONEUROMIOGRAFIA_MEMBROS_SUPERIORES', 'ELETRONEUROMIOGRAFIA_MEMBROS_INFERIORES',
    'CATETERISMO_CARDIACO_ESQUERDO_DIAGNOSTICO', 'AVALIACAO_URODINAMICA_COMPLETA',
    'EXERESE_PEQUENAS_LESOES_PELE_ANATOMOPATOLOGICO'
));